"""
Data Types
===========

Core data structures used throughout the trading system.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional
from enum import Enum
from decimal import Decimal


class Side(Enum):
    """Order side."""
    BUY = "buy"
    SELL = "sell"
    
    @property
    def opposite(self) -> 'Side':
        return Side.SELL if self == Side.BUY else Side.BUY


class OrderType(Enum):
    """Order type."""
    MARKET = "market"
    LIMIT = "limit"
    STOP = "stop"
    STOP_LIMIT = "stop_limit"
    TAKE_PROFIT = "take_profit"
    TAKE_PROFIT_LIMIT = "take_profit_limit"
    TRAILING_STOP = "trailing_stop"


class OrderStatus(Enum):
    """Order status."""
    PENDING = "pending"
    SUBMITTED = "submitted"
    OPEN = "open"
    PARTIALLY_FILLED = "partially_filled"
    FILLED = "filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"
    EXPIRED = "expired"


class PositionStatus(Enum):
    """Position status."""
    OPEN = "open"
    CLOSING = "closing"
    CLOSED = "closed"


class SignalType(Enum):
    """Signal type."""
    ENTRY_LONG = "entry_long"
    ENTRY_SHORT = "entry_short"
    EXIT_LONG = "exit_long"
    EXIT_SHORT = "exit_short"
    SCALE_IN = "scale_in"
    SCALE_OUT = "scale_out"
    ADJUST_STOP = "adjust_stop"
    ADJUST_TARGET = "adjust_target"


class Regime(Enum):
    """Market regime."""
    TRENDING_UP = "trending_up"
    TRENDING_DOWN = "trending_down"
    RANGING = "ranging"
    HIGH_VOLATILITY = "high_volatility"
    LOW_VOLATILITY = "low_volatility"
    UNKNOWN = "unknown"


class Session(Enum):
    """Trading session."""
    ASIA = "asia"
    LONDON = "london"
    NEW_YORK = "new_york"
    OVERLAP_ASIA_LONDON = "overlap_asia_london"
    OVERLAP_LONDON_NY = "overlap_london_ny"
    WEEKEND = "weekend"


@dataclass
class Candle:
    """OHLCV candle data."""
    symbol: str
    timeframe: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float
    
    @property
    def is_bullish(self) -> bool:
        return self.close > self.open
    
    @property
    def is_bearish(self) -> bool:
        return self.close < self.open
    
    @property
    def body_size(self) -> float:
        return abs(self.close - self.open)
    
    @property
    def range(self) -> float:
        return self.high - self.low
    
    @property
    def upper_wick(self) -> float:
        return self.high - max(self.open, self.close)
    
    @property
    def lower_wick(self) -> float:
        return min(self.open, self.close) - self.low
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "symbol": self.symbol,
            "timeframe": self.timeframe,
            "timestamp": self.timestamp.isoformat(),
            "open": self.open,
            "high": self.high,
            "low": self.low,
            "close": self.close,
            "volume": self.volume,
        }


@dataclass
class Tick:
    """Price tick data."""
    symbol: str
    timestamp: datetime
    bid: float
    ask: float
    last: float
    volume: float = 0.0
    
    @property
    def mid(self) -> float:
        return (self.bid + self.ask) / 2
    
    @property
    def spread(self) -> float:
        return self.ask - self.bid
    
    @property
    def spread_pct(self) -> float:
        return (self.spread / self.mid) * 100 if self.mid else 0


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    signal_id: str
    strategy_name: str
    strategy_version: str
    symbol: str
    signal_type: SignalType
    timestamp: datetime
    price: float
    confidence: float = 1.0
    
    # Entry details
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profits: List[Dict[str, float]] = field(default_factory=list)  # [{price, pct}]
    
    # Signal context
    timeframe: str = ""
    bias_timeframe: str = ""
    bias_direction: Optional[str] = None
    
    # Indicator values at signal time
    indicators: Dict[str, float] = field(default_factory=dict)
    
    # Risk assessment
    risk_reward_ratio: float = 0.0
    position_size_suggestion: Optional[float] = None
    
    # Metadata
    reason: str = ""
    tags: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    # Filtering
    filtered: bool = False
    filter_reason: str = ""
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "signal_id": self.signal_id,
            "strategy_name": self.strategy_name,
            "strategy_version": self.strategy_version,
            "symbol": self.symbol,
            "signal_type": self.signal_type.value,
            "timestamp": self.timestamp.isoformat(),
            "price": self.price,
            "confidence": self.confidence,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "take_profits": self.take_profits,
            "timeframe": self.timeframe,
            "indicators": self.indicators,
            "risk_reward_ratio": self.risk_reward_ratio,
            "reason": self.reason,
            "tags": self.tags,
        }


@dataclass
class Order:
    """Order representation."""
    order_id: str
    client_order_id: str
    symbol: str
    side: Side
    order_type: OrderType
    quantity: float
    price: Optional[float] = None
    stop_price: Optional[float] = None
    
    # Status
    status: OrderStatus = OrderStatus.PENDING
    filled_quantity: float = 0.0
    average_fill_price: float = 0.0
    
    # Timestamps
    created_at: datetime = field(default_factory=datetime.utcnow)
    submitted_at: Optional[datetime] = None
    filled_at: Optional[datetime] = None
    cancelled_at: Optional[datetime] = None
    
    # Execution details
    exchange: str = ""
    exchange_order_id: str = ""
    commission: float = 0.0
    commission_asset: str = ""
    slippage: float = 0.0
    
    # Options
    post_only: bool = False
    reduce_only: bool = False
    time_in_force: str = "GTC"  # GTC, IOC, FOK
    
    # Linking
    signal_id: str = ""
    position_id: str = ""
    parent_order_id: str = ""
    
    # Retry management
    retry_count: int = 0
    last_error: str = ""
    
    @property
    def is_filled(self) -> bool:
        return self.status == OrderStatus.FILLED
    
    @property
    def is_open(self) -> bool:
        return self.status in [OrderStatus.OPEN, OrderStatus.SUBMITTED, OrderStatus.PARTIALLY_FILLED]
    
    @property
    def remaining_quantity(self) -> float:
        return self.quantity - self.filled_quantity
    
    @property
    def fill_pct(self) -> float:
        return (self.filled_quantity / self.quantity * 100) if self.quantity else 0
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "order_id": self.order_id,
            "client_order_id": self.client_order_id,
            "symbol": self.symbol,
            "side": self.side.value,
            "order_type": self.order_type.value,
            "quantity": self.quantity,
            "price": self.price,
            "stop_price": self.stop_price,
            "status": self.status.value,
            "filled_quantity": self.filled_quantity,
            "average_fill_price": self.average_fill_price,
            "created_at": self.created_at.isoformat(),
            "exchange": self.exchange,
            "exchange_order_id": self.exchange_order_id,
        }


@dataclass
class Position:
    """Position representation with lifecycle management."""
    position_id: str
    symbol: str
    side: Side
    status: PositionStatus = PositionStatus.OPEN
    
    # Size and price
    quantity: float = 0.0
    entry_price: float = 0.0
    current_price: float = 0.0
    
    # Lifecycle management
    stop_loss: Optional[float] = None
    original_stop_loss: Optional[float] = None
    trailing_stop_distance: Optional[float] = None
    trailing_stop_activated: bool = False
    
    take_profits: List[Dict[str, Any]] = field(default_factory=list)  # [{price, quantity, filled}]
    break_even_triggered: bool = False
    
    # Timestamps
    opened_at: datetime = field(default_factory=datetime.utcnow)
    closed_at: Optional[datetime] = None
    max_favorable_excursion_time: Optional[datetime] = None
    max_adverse_excursion_time: Optional[datetime] = None
    
    # Performance tracking
    realized_pnl: float = 0.0
    unrealized_pnl: float = 0.0
    max_favorable_excursion: float = 0.0  # Best unrealized profit
    max_adverse_excursion: float = 0.0    # Worst unrealized loss
    
    # Commission and fees
    total_commission: float = 0.0
    
    # Metadata
    strategy_name: str = ""
    strategy_version: str = ""
    signal_id: str = ""
    entry_reason: str = ""
    exit_reason: str = ""
    tags: List[str] = field(default_factory=list)
    
    # Orders
    entry_orders: List[str] = field(default_factory=list)
    exit_orders: List[str] = field(default_factory=list)
    stop_orders: List[str] = field(default_factory=list)
    take_profit_orders: List[str] = field(default_factory=list)
    
    @property
    def is_long(self) -> bool:
        return self.side == Side.BUY
    
    @property
    def is_short(self) -> bool:
        return self.side == Side.SELL
    
    @property
    def is_open(self) -> bool:
        return self.status == PositionStatus.OPEN
    
    @property
    def notional_value(self) -> float:
        return self.quantity * self.current_price
    
    @property
    def duration_seconds(self) -> float:
        end_time = self.closed_at or datetime.utcnow()
        return (end_time - self.opened_at).total_seconds()
    
    @property
    def duration_minutes(self) -> float:
        return self.duration_seconds / 60
    
    @property
    def pnl_pct(self) -> float:
        if not self.entry_price:
            return 0.0
        if self.is_long:
            return ((self.current_price - self.entry_price) / self.entry_price) * 100
        else:
            return ((self.entry_price - self.current_price) / self.entry_price) * 100
    
    def update_price(self, price: float) -> None:
        """Update current price and track excursions."""
        self.current_price = price
        
        # Calculate unrealized PnL
        if self.is_long:
            self.unrealized_pnl = (price - self.entry_price) * self.quantity
        else:
            self.unrealized_pnl = (self.entry_price - price) * self.quantity
        
        # Track maximum favorable excursion
        if self.unrealized_pnl > self.max_favorable_excursion:
            self.max_favorable_excursion = self.unrealized_pnl
            self.max_favorable_excursion_time = datetime.utcnow()
        
        # Track maximum adverse excursion
        if self.unrealized_pnl < self.max_adverse_excursion:
            self.max_adverse_excursion = self.unrealized_pnl
            self.max_adverse_excursion_time = datetime.utcnow()
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "position_id": self.position_id,
            "symbol": self.symbol,
            "side": self.side.value,
            "status": self.status.value,
            "quantity": self.quantity,
            "entry_price": self.entry_price,
            "current_price": self.current_price,
            "stop_loss": self.stop_loss,
            "take_profits": self.take_profits,
            "unrealized_pnl": self.unrealized_pnl,
            "realized_pnl": self.realized_pnl,
            "opened_at": self.opened_at.isoformat(),
            "strategy_name": self.strategy_name,
        }


@dataclass
class Trade:
    """Completed trade record."""
    trade_id: str
    position_id: str
    symbol: str
    side: Side
    
    # Execution
    entry_price: float
    exit_price: float
    quantity: float
    
    # PnL
    gross_pnl: float
    commission: float
    net_pnl: float
    pnl_pct: float
    
    # Timing
    entry_time: datetime
    exit_time: datetime
    duration_seconds: float
    
    # Excursions
    max_favorable_excursion: float = 0.0
    max_adverse_excursion: float = 0.0
    
    # Strategy info
    strategy_name: str = ""
    strategy_version: str = ""
    entry_reason: str = ""
    exit_reason: str = ""
    
    # Slippage
    entry_slippage: float = 0.0
    exit_slippage: float = 0.0
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "trade_id": self.trade_id,
            "position_id": self.position_id,
            "symbol": self.symbol,
            "side": self.side.value,
            "entry_price": self.entry_price,
            "exit_price": self.exit_price,
            "quantity": self.quantity,
            "gross_pnl": self.gross_pnl,
            "commission": self.commission,
            "net_pnl": self.net_pnl,
            "pnl_pct": self.pnl_pct,
            "entry_time": self.entry_time.isoformat(),
            "exit_time": self.exit_time.isoformat(),
            "duration_seconds": self.duration_seconds,
            "strategy_name": self.strategy_name,
            "entry_reason": self.entry_reason,
            "exit_reason": self.exit_reason,
        }


@dataclass
class AccountBalance:
    """Account balance snapshot."""
    timestamp: datetime
    total_equity: float
    available_balance: float
    used_margin: float
    unrealized_pnl: float
    realized_pnl_today: float
    
    # Currency breakdown
    balances: Dict[str, float] = field(default_factory=dict)
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "timestamp": self.timestamp.isoformat(),
            "total_equity": self.total_equity,
            "available_balance": self.available_balance,
            "used_margin": self.used_margin,
            "unrealized_pnl": self.unrealized_pnl,
            "realized_pnl_today": self.realized_pnl_today,
            "balances": self.balances,
        }


@dataclass
class RiskMetrics:
    """Current risk metrics snapshot."""
    timestamp: datetime
    
    # Daily metrics
    daily_pnl: float = 0.0
    daily_pnl_pct: float = 0.0
    daily_trades: int = 0
    daily_wins: int = 0
    daily_losses: int = 0
    
    # Consecutive metrics
    consecutive_wins: int = 0
    consecutive_losses: int = 0
    
    # Drawdown
    peak_equity: float = 0.0
    current_equity: float = 0.0
    current_drawdown: float = 0.0
    current_drawdown_pct: float = 0.0
    max_drawdown: float = 0.0
    max_drawdown_pct: float = 0.0
    
    # Exposure
    total_exposure: float = 0.0
    exposure_pct: float = 0.0
    position_count: int = 0
    
    # Risk limits status
    daily_loss_limit_pct: float = 0.0
    drawdown_limit_pct: float = 0.0
    is_trading_allowed: bool = True
    limit_breach_reason: str = ""
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "timestamp": self.timestamp.isoformat(),
            "daily_pnl": self.daily_pnl,
            "daily_pnl_pct": self.daily_pnl_pct,
            "consecutive_losses": self.consecutive_losses,
            "current_drawdown_pct": self.current_drawdown_pct,
            "max_drawdown_pct": self.max_drawdown_pct,
            "total_exposure": self.total_exposure,
            "is_trading_allowed": self.is_trading_allowed,
            "limit_breach_reason": self.limit_breach_reason,
        }
